# Lab 2: Python Basics, NumPy & Pandas

**Author:** Arslan Hashmi  
**Track:** AI/ML Internship Program | Week 1  
**Institution:** National University of Technology (NUTECH)

---

Welcome to Lab 2! This notebook is your starting point for the Python skills you will use throughout this internship: core Python, NumPy (numerical computing), and Pandas (working with real tabular data).

**After this lab you will be able to:**
- Use Python's core data structures and functions comfortably
- Understand and use NumPy arrays, vectorized operations, and broadcasting
- Load, explore, and manipulate data using Pandas

**Instructions:**
- Write your code between the `### YOUR CODE HERE ###` and `### END ###` markers.
- Run each cell with **Shift + Enter**.
- Compare your output with the **Expected Output** shown below each exercise.
- Try to avoid explicit `for`/`while` loops in the NumPy section unless the exercise asks for one — this is where vectorization comes in.

## How to Use This Notebook

This is a Jupyter/Colab-style notebook made up of two types of cells: **markdown cells** (like this one, for explanations) and **code cells** (where you write and run Python). Run a code cell by clicking it and pressing Shift+Enter — the output appears directly underneath. Variables defined in one cell are available in every cell after it, as long as that cell has already been run.

Let's begin.

## Part 1 — Python Basics Refresher

### 1.1 Variables & F-Strings

Python does not require you to declare a variable's type — it is inferred automatically. f-strings (`f"..."`) are the cleanest way to build strings that include variable values.

**Exercise:** Create three variables — `student_name` (a string), `week_number` (an int), and `score` (a float) — with values of your choice. Then build a single string called `summary` using an f-string in the form: `"<name> is in week <week_number> with a score of <score>"`.

In [ ]:
student_name = None
week_number = None
score = None
summary = None

### YOUR CODE HERE ###
student_name = "Arslan Hashmi"
week_number = 1
score = 92.5
summary = f"{student_name} is in week {week_number} with a score of {score}"
### END ###

print(summary)

**Expected Output (example):**
```
Arslan Hashmi is in week 1 with a score of 92.5
```

### 1.2 Lists & Comprehensions

A list comprehension builds a new list from an existing one in a single line, and is used constantly in data work instead of longer loops.

**Exercise:** Given the list `daily_visitors` below, use a list comprehension to create `high_traffic_days`, containing only the values greater than 200.

In [ ]:
daily_visitors = [180, 220, 95, 310, 150, 275, 400]
high_traffic_days = None

### YOUR CODE HERE ###
high_traffic_days = [v for v in daily_visitors if v > 200]
### END ###

print(high_traffic_days)

**Expected Output:**
```
[220, 310, 275, 400]
```

### 1.3 Dictionaries

Dictionaries map keys to values and are the closest Python equivalent to a real-world lookup table or a single row of structured data.

**Exercise:** Create a dictionary called `product` with keys `"name"`, `"price"`, and `"in_stock"`, using values of your choice. Then write a single f-string, `product_summary`, describing the product using all three values.

In [ ]:
product = None
product_summary = None

### YOUR CODE HERE ###
product = {
    "name": "Wireless Mouse",
    "price": 19.99,
    "in_stock": True
}
product_summary = f"{product['name']} is priced at ${product['price']} and is currently in stock."
### END ###

print(product_summary)

**Expected Output (example):**
```
Wireless Mouse is priced at $19.99 and is currently in stock.
```

### 1.4 Functions & Conditionals

**Exercise:** Write a function `classify_score(score)` that returns `"Excellent"` if the score is 90 or above, `"Good"` if it is between 70 (inclusive) and 90, and `"Needs Improvement"` otherwise. Test it on three different values.

In [ ]:
def classify_score(score):
    ### YOUR CODE HERE ###
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    else:
        return "Needs Improvement"
    ### END ###

print(classify_score(95))
print(classify_score(75))
print(classify_score(40))

**Expected Output:**
```
Excellent
Good
Needs Improvement
```

**What to remember from Part 1:**
- f-strings are the cleanest way to build strings with variable values
- List comprehensions replace many simple loops
- Dictionaries are Python's key-value lookup structure
- Functions with clear return values are easier to test and reuse

Now that the Python refresher is done, let's move to NumPy — the library almost every data and ML tool in Python is built on top of.

## Part 2 — NumPy Essentials

NumPy's core object is the **array**. Unlike a plain Python list, arrays support **vectorized operations** — applying a computation to every element at once, without writing a loop — which makes them both faster and easier to read.

### 2.1 Creating Arrays

In [ ]:
import numpy as np

# Example: converting a list to a NumPy array
temperatures = [22, 25, 19, 30, 28]
temp_array = np.array(temperatures)

print(temp_array)
print(temp_array.shape)
print(temp_array.dtype)

### 2.2 Vectorized Operations

**Exercise:** Given the array `prices` below, create `discounted_prices`, where every value has a 15% discount applied — without using a loop.

In [ ]:
prices = np.array([1200, 850, 430, 999, 75])
discounted_prices = None

### YOUR CODE HERE ###
discounted_prices = prices * 0.85
### END ###

print(discounted_prices)

**Expected Output:**
```
[1020.   722.5  365.5  849.15  63.75]
```

### 2.3 Min-Max Normalization

A common preprocessing step in ML is scaling values into a fixed range, typically [0, 1]. The formula for min-max normalization is:

$$ x_{norm} = \frac{x - min(x)}{max(x) - min(x)} $$

**Exercise:** Implement `normalize(x)`, which takes a NumPy array and returns it min-max normalized. Use `np.min()` and `np.max()` — no loops.

In [ ]:
def normalize(x):
    ### YOUR CODE HERE ###
    return (x - np.min(x)) / (np.max(x) - np.min(x))
    ### END ###

test_scores = np.array([40, 55, 70, 85, 100])
print(normalize(test_scores))

**Expected Output:**
```
[0.   0.25 0.5  0.75 1.  ]
```

### 2.4 Reshaping Arrays

`array.shape` tells you an array's dimensions, and `array.reshape(...)` lets you rearrange it into a different shape (as long as the total number of elements matches).

**Exercise:** Given the flat array `readings` (12 sensor readings), reshape it into a 3x4 matrix called `readings_matrix`, then compute the mean of each row using `axis=1`.

In [ ]:
readings = np.array([12, 15, 14, 18, 20, 19, 17, 16, 22, 21, 20, 19])
readings_matrix = None
row_means = None

### YOUR CODE HERE ###
readings_matrix = readings.reshape(3, 4)
row_means = readings_matrix.mean(axis=1)
### END ###

print(readings_matrix)
print(row_means)

**Expected Output:**
```
[[12 15 14 18]
 [20 19 17 16]
 [22 21 20 19]]
[14.75 18.   20.5 ]
```

### 2.5 Broadcasting

Broadcasting lets NumPy apply an operation between arrays of different shapes without manually looping — for example, subtracting a single row of column-averages from every row of a matrix.

**Exercise:** Using `readings_matrix` from the previous exercise, subtract the column-wise mean (`axis=0`) from every row, producing `centered_matrix`.

In [ ]:
centered_matrix = None

### YOUR CODE HERE ###
centered_matrix = readings_matrix - readings_matrix.mean(axis=0)
### END ###

print(centered_matrix)

### 2.6 Why Vectorization Matters

Run the cell below as-is to compare a manual loop against NumPy's vectorized `np.dot()` for computing a dot product on a larger array. Note the difference in computation time.

In [ ]:
import time

a = list(range(1_000_000))
b = list(range(1_000_000))

# Manual loop
tic = time.process_time()
loop_dot = 0
for i in range(len(a)):
    loop_dot += a[i] * b[i]
toc = time.process_time()
print("Loop result:", loop_dot, "| Time:", (toc - tic) * 1000, "ms")

# Vectorized with NumPy
a_np = np.array(a)
b_np = np.array(b)

tic = time.process_time()
vec_dot = np.dot(a_np, b_np)
toc = time.process_time()
print("Vectorized result:", vec_dot, "| Time:", (toc - tic) * 1000, "ms")

**What to remember from Part 2:**
- NumPy arrays support vectorized operations — no loops needed for element-wise math
- `.reshape()` changes an array's dimensions without changing its data
- Broadcasting lets you operate between arrays of different (but compatible) shapes
- Vectorized NumPy code is dramatically faster than an equivalent manual loop

Now let's move to Pandas, which is built on top of NumPy and is the standard tool for working with real, tabular datasets.

## Part 3 — Pandas Essentials

Pandas' main object is the **DataFrame** — a table of rows and columns, similar to a spreadsheet, but fully controllable through code.

### 3.1 Creating and Exploring a DataFrame

In [ ]:
import pandas as pd

data = {
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Webcam"],
    "price": [1200, 25, 45, 300, 60],
    "units_sold": [15, 120, 95, 40, 70]
}
df = pd.DataFrame(data)

df.head()

In [ ]:
df.info()

In [ ]:
df.describe()

### 3.2 Filtering & Creating New Columns

**Exercise:** Create a new column `revenue` equal to `price * units_sold`. Then create a filtered DataFrame `high_revenue` containing only rows where `revenue` is above 5000.

In [ ]:
df["revenue"] = None
high_revenue = None

### YOUR CODE HERE ###
df["revenue"] = df["price"] * df["units_sold"]
high_revenue = df[df["revenue"] > 5000]
### END ###

print(high_revenue)

### 3.3 Grouping & Aggregating

**Exercise:** Using the `products_extended` DataFrame below (which has a `category` column), compute the average `price` and total `units_sold` per category, in a single `.groupby().agg()` call.

In [ ]:
products_extended = pd.DataFrame({
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Webcam", "Desk", "Chair"],
    "category": ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Furniture", "Furniture"],
    "price": [1200, 25, 45, 300, 60, 250, 180],
    "units_sold": [15, 120, 95, 40, 70, 20, 35]
})

category_summary = None

### YOUR CODE HERE ###
category_summary = products_extended.groupby("category").agg(
    avg_price=("price", "mean"),
    total_units=("units_sold", "sum")
)
### END ###

print(category_summary)

### 3.4 Handling Missing Values

**Exercise:** The DataFrame below has missing values in the `price` column. Create `df_filled`, where missing prices are replaced with the column's average price, using `.fillna()`.

In [ ]:
import numpy as np

messy_data = pd.DataFrame({
    "product": ["Tablet", "Charger", "Case", "Earbuds"],
    "price": [400, np.nan, 20, np.nan]
})

df_filled = None

### YOUR CODE HERE ###
df_filled = messy_data.copy()
df_filled["price"] = df_filled["price"].fillna(df_filled["price"].mean())
### END ###

print(df_filled)

**What to remember from Part 3:**
- A DataFrame is a table you can filter, transform, and summarize entirely through code
- New columns can be created directly from existing ones
- `.groupby().agg()` is the standard way to summarize data by category
- `.fillna()` is one common way to handle missing values — the right strategy depends on the situation

## Lab Tasks

Complete the following tasks in this notebook, below this cell. These bring together everything covered above.

1. **Personal Data Profile:** Create a dictionary describing yourself (name, role, program week, etc.), then write a function `format_profile(profile_dict)` that returns a formatted, readable summary string built from it.
2. **NumPy Analysis:** Create a NumPy array of at least 10 numbers representing any data of your choice (e.g., daily task counts, temperatures). Compute and print its mean, standard deviation, and the count of values above the mean — without using any loops.
3. **Custom Normalization:** Reuse your `normalize()` function from Part 2 on your own array from Task 2, and print the result.
4. **Mini Dataset Exploration:** Create a small Pandas DataFrame (at least 5 rows, 3 columns) about any topic of your choice. Add one derived column using a calculation on existing columns, then filter the DataFrame based on a condition of your choice.
5. **Summary:** In a markdown cell below your code, write 3-4 sentences in your own words on what you learned in this lab and which part (Python, NumPy, or Pandas) you found most useful or challenging.

### Task 1 — Personal Data Profile

In [ ]:
profile = {
    "name": "Arslan Hashmi",
    "role": "CS Student & Aspiring AI Engineer",
    "institution": "National University of Technology (NUTECH)",
    "semester": "5th",
    "program": "AI/ML Internship Program",
    "week": 1
}

def format_profile(profile_dict):
    return (
        f"Name: {profile_dict['name']}
"
        f"Role: {profile_dict['role']}
"
        f"Institution: {profile_dict['institution']}
"
        f"Semester: {profile_dict['semester']}
"
        f"Program: {profile_dict['program']} (Week {profile_dict['week']})"
    )

print(format_profile(profile))

### Task 2 — NumPy Analysis

In [ ]:
# Daily study hours over 2 weeks
study_hours = np.array([3.5, 4.0, 2.5, 5.0, 3.0, 4.5, 6.0, 3.5, 4.0, 5.5, 2.0, 4.5, 5.0, 3.0])

mean_hours = study_hours.mean()
std_hours = study_hours.std()
above_mean = (study_hours > mean_hours).sum()

print("Study Hours Array:", study_hours)
print(f"Mean: {mean_hours:.2f}")
print(f"Standard Deviation: {std_hours:.2f}")
print(f"Days above mean: {above_mean}")

### Task 3 — Custom Normalization

In [ ]:
normalized_hours = normalize(study_hours)
print("Normalized Study Hours:")
print(np.round(normalized_hours, 3))

### Task 4 — Mini Dataset Exploration

In [ ]:
courses = pd.DataFrame({
    "course": ["Python Basics", "NumPy & Pandas", "Data Visualization", "ML Fundamentals", "Deep Learning Intro"],
    "hours_spent": [8, 10, 6, 12, 9],
    "difficulty": [2, 3, 3, 4, 5]  # 1 (easy) to 5 (hard)
})

# Derived column: efficiency score (hours / difficulty)
courses["efficiency"] = (courses["hours_spent"] / courses["difficulty"]).round(2)

# Filter courses with high efficiency (> 2.5)
high_efficiency = courses[courses["efficiency"] > 2.5]

print("Full Dataset:")
print(courses)
print("\nHigh Efficiency Courses:")
print(high_efficiency)

### Task 5 — Summary

In this lab I strengthened my foundation in three essential layers of the Python data stack. The **Python basics** section reinforced clean syntax habits (especially f-strings and list comprehensions). The **NumPy** section was the most eye-opening — seeing how vectorized operations and broadcasting eliminate loops and deliver massive speed gains made me appreciate why every serious ML library is built on top of it. **Pandas** felt the most immediately practical for real-world work; creating columns, filtering, and grouping data felt natural and powerful. Overall, NumPy was both the most useful and the most challenging part because thinking in vectors instead of loops takes a mental shift, but it is clearly the key skill for efficient data science work.

---

**Lab completed by Arslan Hashmi**  
AI/ML Internship Program | Week 1  
National University of Technology (NUTECH)